### PR TITLE
New config file

### PR DESCRIPTION
**Pull request by MollyBe**
Defined each button and remapped for personal preference.

### CODE REVIEW

**Comment by BunnyTub** [comment]
This project appears to be abandoned as it hasn't been updated since 2019 and possibly even older.

**Comment by Tylemagne** [comment]
This is actually generated by Gopher itself when it runs. If you want to change the "default" values, they would have to be done in the config file generator.

**Comment by MollyBe** [comment]
It would be useful if the default config had extra information like I've provided in my config file (such as what the key is and what it does). 

I've created this pull request, per the README.md, to share my mapping preference and to add more detail to the config.

> + If you make a config file you feel could benefit people with the same use scenario as you, feel free to make a pull request for it in the public configs directory.

**Comment by csksea** [comment]
is it possible to assign multiple key strokes to a single button?  eg. i want to map (win key + ctrl + r. arrow) to the right trigger button.  i have really bad carpal tunnel and using the xbox controller as a mouse has saved me!  thank you for sharing this amazing application!

**Pull request closed without merging**
